---
- name: ensure VMWare repository GPG key present
  apt_key: >
    url=http://packages.vmware.com/tools/keys/VMWARE-PACKAGING-GPG-RSA-KEY.pub
    state=present
  tags:
    - ubuntu
    - vmware_tools

# there is no version newer than precise. Ticket #168 exists for the migration to open-vm-tools.
- name: ensure VMWare repository present 
  apt_repository: >
    repo='deb http://packages.vmware.com/tools/esx/5.1latest/ubuntu precise main'
  tags:
    - ubuntu
    - vmware_tools

- name: removing source line for VMWare repository (Ubuntu bug)
  lineinfile: >
    dest=/etc/apt/sources.list
    regexp="^deb-src http://packages.vmware"
    state=absent
  tags:
    - ubuntu
    - vmware_tools

- name: ensure VMWare tools is available and installed in to the kernel
  apt: >
    state=latest
    name={{ item }}
  with_items:
    - vmware-tools-foundation
    - vmware-tools-esx-nox
  tags:
    - ubuntu
    - vmware_tools
