---
- name: checking jon .ssh folder exists and is set correct
  file: >
    dest=/home/jon/.ssh
    state=directory
    owner=jon
    group=jon
    mode=700
  tags:
    - ubuntu
    - ubuntu_users

- name: set jon user SSH authorized_keys
  copy: >
    src=../../common/publickeys/authorized_keys
    dest=/home/jon/.ssh/authorized_keys
    owner=jon
    group=jon
    mode=0600
  when: manage_authorized_keys == true
  tags:
    - ubuntu
    - ubuntu_users

