---
galaxy_info:
  author: Rahul Mohandas
  description: Installs and configures oh-my-zsh
  license: MIT
  min_ansible_version: 1.2
  platforms:
  #- name: EL
  #  versions:
  #  - all
  #  - 5
  #  - 6
  #  - 7
  #- name: Fedora
  #  versions:
  #  - all
  #  - 16
  #  - 17
  #  - 18
  #  - 19
  #  - 20
  #  - 21
  #  - 22
  - name: Ubuntu
    versions:
    - all
    - lucid
    - maverick
    - natty
    - oneiric
    - precise
    - quantal
    - raring
    - saucy
    - trusty
    - utopic
    - vivid
  - name: Debian
    versions:
    - all
    - etch
    - jessie
    - lenny
    - squeeze
    - wheezy
  categories:
  - system
dependencies: []
