---
galaxy_info:
  author: Petr Ruzicka
  description: Installation of vmware-tools package and repostory
  company: your company (optional)
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - all
  - name: opensuse
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: SLES
    versions:
    - 11
    - 12
  - name: Debian
    versions:
    - all
  - name: FreeBSD
    versions:
    - all
  categories:
  - cloud
  - system
