---
- name: validation
  assert:
    that:
      - newrelic_license|length == 40

- name: include os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - ../vars/{{ ansible_distribution }}.yml
    - ../vars/{{ ansible_os_family }}.yml
  tags:
    - newrelic

- include: Debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

