---
galaxy_info:
  author: Wirehive Ltd
  description: 
  company: Wirehive Ltd
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
  - name: Debian
    versions:
    - squeeze
    - wheezy
  categories:
  - system
dependencies: 
  - yaegashi.blockinfile
  - linux_harden


  
