---
- hosts: home-servers
  become: yes
  become_method: sudo

  vars_files:
    - private.yml

  roles:
     - common
     - linux_harden
     - newrelic
     - ntp
     - vmwaretools

- hosts: home-servers
  become: no
  become_method: sudo

  roles:
     - oh_my_zsh

